<?php
/**
 * Created by PhpStorm.
 * User: Yuri2
 * Date: 2017/7/26
 * Time: 10:54
 */
return [
    'src\cores\Main' => PATH_GEAR . '/src/cores/Main.php',
    'src\cores\Config' => PATH_GEAR . '/src/cores/Config.php',
    'src\cores\Factory' => PATH_GEAR . '/src/cores/Factory.php',
    'src\cores\Event' => PATH_GEAR . '/src/cores/Event.php',
    'src\cores\PluginManager' => PATH_GEAR . '/src/cores/PluginManager.php',
    'src\traits\Base' => PATH_GEAR . '/src/traits/Base.php',
    'src\traits\Plugin' => PATH_GEAR . '/src/traits/Plugin.php',
    'src\plugins\envCheck\Main' => PATH_GEAR . '/src/plugins/envCheck/Main.php',
    'src\plugins\encrypt\Main' => PATH_GEAR . '/src/plugins/encrypt/Main.php',
    'src\plugins\route\Main' => PATH_GEAR . '/src/plugins/route/Main.php',
    'src\plugins\routeSpecial\Main' => PATH_GEAR . '/src/plugins/routeSpecial/Main.php',
    'src\plugins\routeSpecial\RouteSpecial' => PATH_GEAR . '/src/plugins/routeSpecial/RouteSpecial.php',
    'src\plugins\route\Route' => PATH_GEAR . '/src/plugins/route/Route.php',
    'src\plugins\captcha\Main' => PATH_GEAR . '/src/plugins/captcha/Main.php',
    'src\traits\Ctrl' => PATH_GEAR . '/src/traits/Ctrl.php',
    'src\plugins\errorCatch\Main' => PATH_GEAR . '/src/plugins/errorCatch/Main.php',
    'src\plugins\debug\Main' => PATH_GEAR . '/src/plugins/debug/Main.php',
    'src\plugins\dispatch\Main' => PATH_GEAR . '/src/plugins/dispatch/Main.php',
    'src\plugins\infoJump\Main' => PATH_GEAR . '/src/plugins/infoJump/Main.php',
    'src\plugins\view\Main' => PATH_GEAR . '/src/plugins/view/Main.php',
    'src\plugins\logger\Main' => PATH_GEAR . '/src/plugins/logger/Main.php',
    'src\plugins\formToken\Main' => PATH_GEAR . '/src/plugins/formToken/Main.php',
    'src\plugins\qrCode\Main' => PATH_GEAR . '/src/plugins/qrCode/Main.php',
    'src\plugins\upload\Main' => PATH_GEAR . '/src/plugins/upload/Main.php',
    'src\plugins\db\Main' => PATH_GEAR . '/src/plugins/db/Main.php',
    'src\plugins\dbThink\Main' => PATH_GEAR . '/src/plugins/dbThink/Main.php',
    'src\plugins\cache\Main' => PATH_GEAR . '/src/plugins/cache/Main.php',
    'src\plugins\weiChat\Main' => PATH_GEAR . '/src/plugins/weiChat/Main.php',
    'src\plugins\admin\Main' => PATH_GEAR . '/src/plugins/admin/Main.php',
    'src\plugins\arrayDb\Main' => PATH_GEAR . '/src/plugins/arrayDb/Main.php',
    'src\plugins\picMagic\Main' => PATH_GEAR . '/src/plugins/picMagic/Main.php',
    'src\plugins\picMagic\PicMagic' => PATH_GEAR . '/src/plugins/picMagic/PicMagic.php',
    'src\plugins\ueditor\Main' => PATH_GEAR . '/src/plugins/ueditor/Main.php',
    'src\plugins\webSocket\Main' => PATH_GEAR . '/src/plugins/webSocket/Main.php',
    'src\plugins\factory\Main' => PATH_GEAR . '/src/plugins/factory/Main.php',
    'src\plugins\dispatch\Dispatch' => PATH_GEAR . '/src/plugins/dispatch/Dispatch.php',
    'apps\Home\ctrls\Main' => PATH_GEAR . '/apps/Home/ctrls/Main.php',
    'src\plugins\errorCatch\ErrorCatch' => PATH_GEAR . '/src/plugins/errorCatch/ErrorCatch.php',
    'src\plugins\debug\Debug' => PATH_GEAR . '/src/plugins/debug/Debug.php',
    'src\plugins\encrypt\Encrypt' => PATH_GEAR . '/src/plugins/encrypt/Encrypt.php',
    'src\plugins\factory\libs\Cookie' => PATH_GEAR . '/src/plugins/factory/libs/Cookie.php',
    'src\plugins\factory\libs\Excel' => PATH_GEAR . '/src/plugins/factory/libs/Excel.php',
    'src\plugins\factory\libs\File' => PATH_GEAR . '/src/plugins/factory/libs/File.php',
    'src\plugins\factory\libs\Format' => PATH_GEAR . '/src/plugins/factory/libs/Format.php',
    'src\plugins\factory\libs\Image' => PATH_GEAR . '/src/plugins/factory/libs/Image.php',
    'src\plugins\factory\libs\Locker' => PATH_GEAR . '/src/plugins/factory/libs/Locker.php',
    'src\plugins\factory\libs\NeuralNetwork' => PATH_GEAR . '/src/plugins/factory/libs/NeuralNetwork.php',
    'src\plugins\factory\libs\Parsedown' => PATH_GEAR . '/src/plugins/factory/libs/Parsedown.php',
    'src\plugins\factory\libs\Request' => PATH_GEAR . '/src/plugins/factory/libs/Request.php',
    'src\plugins\factory\libs\Semaphore' => PATH_GEAR . '/src/plugins/factory/libs/Semaphore.php',
    'src\plugins\factory\libs\Sender' => PATH_GEAR . '/src/plugins/factory/libs/Sender.php',
    'src\plugins\factory\libs\Session' => PATH_GEAR . '/src/plugins/factory/libs/Session.php',
];